const fs = require('fs');
const path = require('path');

function safeName(name) {
  return String(name || 'mahani_app')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .replace(/_+/g, '_') || 'mahani_app';
}

function normalizePlan(plan) {
  const p = plan || {};

  return {
    appName: p.appName || 'Mahani App',
    description: p.description || 'Generated by Mahani Builder AI',
    platform: p.platform || 'android',
    features: Array.isArray(p.features) ? p.features : [],
    screens: Array.isArray(p.screens) ? p.screens : [],
    data: p.data && typeof p.data === 'object' ? p.data : {},
    design: {
      style: p.design?.style || 'modern',
      direction: p.design?.direction || 'rtl',
      primaryColor: p.design?.primaryColor || '#1565C0'
    },
    files: Array.isArray(p.files) ? p.files : [],
    dependencies:
      p.dependencies && typeof p.dependencies === 'object'
        ? p.dependencies
        : {}
  };
}

function safeDartFileName(filePath) {
  const value = String(filePath || '').trim();

  if (!value.startsWith('lib/')) return null;
  if (!value.endsWith('.dart')) return null;
  if (value.includes('..')) return null;
  if (value.includes('\\')) return null;

  return value;
}

function createPubspec(projectName, plan) {
  const name = safeName(projectName);

  const description = String(plan.description || '')
    .replace(/\r?\n/g, ' ')
    .replace(/:/g, '-')
    .trim();

  const dependencies = {
    'cupertino_icons': '^1.0.8',
    'provider': '^6.1.2',
    'sqflite': '^2.4.2',
    'path': '^1.9.1',
    'shared_preferences': '^2.5.3',
    'intl': '^0.20.2',
    'flutter_local_notifications': '^19.4.0',
    'pdf': '^3.11.3',
    'printing': '^5.14.2',
    'excel': '^4.0.6',
    'file_picker': '^10.3.3',
    'permission_handler': '^12.0.1',
    'path_provider': '^2.1.5',
    'http': '^1.5.0',
    'uuid': '^4.5.1',
    'crypto': '^3.0.6'
  };

  for (const [key, value] of Object.entries(plan.dependencies)) {
    if (
      typeof key === 'string' &&
      typeof value === 'string' &&
      /^[a-zA-Z0-9_]+$/.test(key)
    ) {
      dependencies[key] = value;
    }
  }

  const dependencyText = Object.entries(dependencies)
    .map(([key, value]) => `  ${key}: ${value}`)
    .join('\n');

  return `name: ${name}
description: ${description || 'Generated by Mahani Builder AI'}
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

${dependencyText}

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
`;
}

function createReadme(projectName, plan) {
  return `# ${plan.appName || projectName}

${plan.description || ''}

## Generated by Mahani Builder AI

Platform: ${plan.platform}

Direction: ${plan.design?.direction || 'rtl'}

## Architecture

This project is generated using a production-oriented Flutter architecture.

Layers:

- Presentation
- Application
- Domain
- Infrastructure

## Features

${plan.features.map(x => `- ${x}`).join('\n')}

## Build

\`\`\`bash
flutter pub get
flutter analyze
flutter build apk --release
\`\`\`
`;
}

function createBuildWorkflow(projectName) {
  const name = safeName(projectName);

  return `name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.7'
          channel: stable
          cache: true

      - name: Create Android platform
        run: |
          rm -rf /tmp/flutter_template
          flutter create --platforms=android --project-name ${name} /tmp/flutter_template
          rm -rf android
          cp -r /tmp/flutter_template/android android

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze project
        run: flutter analyze

      - name: Build release APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ${name}-apk
          path: build/app/outputs/flutter-apk/app-release.apk
`;
}

function createDirectories(root) {
  const directories = [
    'lib',
    'lib/core',
    'lib/core/constants',
    'lib/core/database',
    'lib/core/errors',
    'lib/core/theme',
    'lib/core/utils',
    'lib/domain',
    'lib/domain/entities',
    'lib/domain/repositories',
    'lib/application',
    'lib/application/services',
    'lib/infrastructure',
    'lib/infrastructure/database',
    'lib/infrastructure/repositories',
    'lib/presentation',
    'lib/presentation/screens',
    'lib/presentation/widgets',
    'lib/presentation/providers',
    'test',
    '.github',
    '.github/workflows'
  ];

  for (const dir of directories) {
    fs.mkdirSync(path.join(root, dir), {
      recursive: true
    });
  }
}

function createBaseMain(plan) {
  const color = String(plan.design?.primaryColor || '#1565C0')
    .replace(/[^#a-fA-F0-9]/g, '')
    .slice(0, 7);

  const safeColor = /^#[0-9a-fA-F]{6}$/.test(color)
    ? color
    : '#1565C0';

  return `import 'package:flutter/material.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const MahaniApp());
}

class MahaniApp extends StatelessWidget {
  const MahaniApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: ${JSON.stringify(plan.appName)},
      theme: ThemeData(
        useMaterial3: true,
        colorSchemeSeed: Color(0xFF${safeColor.substring(1)}),
        fontFamily: 'sans',
      ),
      builder: (context, child) {
        return Directionality(
          textDirection: TextDirection.rtl,
          child: child ?? const SizedBox.shrink(),
        );
      },
      home: const Scaffold(
        body: Center(
          child: Text(
            'تم إنشاء المشروع بنجاح',
            textAlign: TextAlign.center,
          ),
        ),
      ),
    );
  }
}
`;
}

function createGitignore() {
  return `# Flutter
.dart_tool/
.flutter-plugins
.flutter-plugins-dependencies
.pub-cache/
build/

# Android
.gradle/
.idea/

# Generated
*.iml

# Local
.env
`;
}

function generateDynamicFiles(root, plan) {
  const files = Array.isArray(plan.files) ? plan.files : [];

  let written = 0;

  for (const file of files) {
    if (!file || typeof file !== 'object') continue;

    const filePath = safeDartFileName(file.path);
    if (!filePath) continue;

    const content = String(file.content || '').trim();

    if (!content) continue;

    const fullPath = path.resolve(root, filePath);
    const libRoot = path.resolve(root, 'lib');

    if (!fullPath.startsWith(libRoot + path.sep)) {
      continue;
    }

    fs.mkdirSync(path.dirname(fullPath), {
      recursive: true
    });

    fs.writeFileSync(
      fullPath,
      content + '\n',
      'utf8'
    );

    written++;
  }

  return written;
}

function createFlutterBase(projectName, plan) {
  plan = normalizePlan(plan);

  const root = path.join(
    __dirname,
    'projects',
    safeName(projectName)
  );

  console.log('[GENERATOR] إنشاء مشروع Enterprise');
  console.log('[GENERATOR] Project:', plan.appName);
  console.log('[GENERATOR] Root:', root);

  fs.rmSync(root, {
    recursive: true,
    force: true
  });

  createDirectories(root);

  fs.writeFileSync(
    path.join(root, 'pubspec.yaml'),
    createPubspec(projectName, plan),
    'utf8'
  );

  fs.writeFileSync(
    path.join(root, 'README.md'),
    createReadme(projectName, plan),
    'utf8'
  );

  fs.writeFileSync(
    path.join(root, '.gitignore'),
    createGitignore(),
    'utf8'
  );

  fs.writeFileSync(
    path.join(root, 'lib', 'main.dart'),
    createBaseMain(plan),
    'utf8'
  );

  fs.writeFileSync(
    path.join(
      root,
      '.github',
      'workflows',
      'build-apk.yml'
    ),
    createBuildWorkflow(projectName),
    'utf8'
  );

  const writtenFiles = generateDynamicFiles(
    root,
    plan
  );

  console.log(
    '[GENERATOR] ملفات AI:',
    plan.files.length
  );

  console.log(
    '[GENERATOR] ملفات مكتوبة:',
    writtenFiles
  );

  return root;
}

module.exports = {
  createFlutterBase,
  safeName,
  normalizePlan
};
