const fs = require('fs');
const path = require('path');

function safeName(name) {
  return String(name || 'mahani_app')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .replace(/_+/g, '_') || 'mahani_app';
}

function normalizePlan(plan) {
  const p = plan || {};

  return {
    appName: p.appName || 'Mahani App',
    description: p.description || '',
    platform: p.platform || 'android',
    features: Array.isArray(p.features) ? p.features : [],
    screens: Array.isArray(p.screens) ? p.screens : [],
    data: p.data && typeof p.data === 'object' ? p.data : {},
    design: {
      style: p.design?.style || 'modern',
      direction: p.design?.direction || 'rtl',
      primaryColor: p.design?.primaryColor || '#2E7D32'
    },
    files: Array.isArray(p.files) ? p.files : []
  };
}

function safeDartFileName(filePath) {
  const value = String(filePath || '').trim();

  if (!value.startsWith('lib/')) return null;
  if (!value.endsWith('.dart')) return null;
  if (value.includes('..')) return null;
  if (value.includes('\\')) return null;

  return value;
}

function createPubspec(projectName, plan) {
  const name = safeName(projectName);
  const description = String(plan.description || '')
    .replace(/\r?\n/g, ' ')
    .replace(/:/g, '-')
    .trim();

  return `name: ${name}
description: ${description || 'Generated by Mahani Builder AI'}
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
`;
}

function createReadme(projectName, plan) {
  return `# ${plan.appName || projectName}

${plan.description || ''}

Generated by Mahani Builder AI.

Platform: ${plan.platform || 'android'}
Direction: ${plan.design?.direction || 'rtl'}
`;
}

function createBuildWorkflow(projectName) {
  const name = safeName(projectName);

  return `name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.7'
          channel: stable

      - name: Create Android platform
        run: |
          rm -rf /tmp/flutter_template
          flutter create --platforms=android --project-name ${name} /tmp/flutter_template
          rm -rf android
          cp -r /tmp/flutter_template/android android

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ${name}-apk
          path: build/app/outputs/flutter-apk/app-release.apk
`;
}

function generateDynamicFiles(root, plan) {
  const files = Array.isArray(plan.files) ? plan.files : [];

  let written = 0;

  for (const file of files) {
    if (!file || typeof file !== 'object') continue;

    const filePath = safeDartFileName(file.path);
    if (!filePath) continue;

    const content = String(file.content || '').trim();

    if (!content) continue;

    const fullPath = path.resolve(root, filePath);
    const libRoot = path.resolve(root, 'lib');

    if (!fullPath.startsWith(libRoot + path.sep)) {
      continue;
    }

    fs.mkdirSync(path.dirname(fullPath), { recursive: true });
    fs.writeFileSync(fullPath, content + '\n', 'utf8');

    written++;
  }

  return written;
}

function createFlutterBase(projectName, plan) {
  plan = normalizePlan(plan);

  console.log('[GENERATOR] بدء إنشاء مشروع حقيقي');
  console.log('[GENERATOR] Project:', plan.appName || projectName);

  const root = path.join(
    __dirname,
    'projects',
    safeName(projectName)
  );

  console.log('[GENERATOR] Root:', root);

  fs.rmSync(root, {
    recursive: true,
    force: true
  });

  fs.mkdirSync(path.join(root, 'lib'), {
    recursive: true
  });

  fs.mkdirSync(path.join(root, '.github', 'workflows'), {
    recursive: true
  });

  fs.writeFileSync(
    path.join(root, 'pubspec.yaml'),
    createPubspec(projectName, plan),
    'utf8'
  );

  fs.writeFileSync(
    path.join(root, 'README.md'),
    createReadme(projectName, plan),
    'utf8'
  );

  fs.writeFileSync(
    path.join(root, '.github', 'workflows', 'build-apk.yml'),
    createBuildWorkflow(projectName),
    'utf8'
  );

  const writtenFiles = generateDynamicFiles(root, plan);

  console.log('[GENERATOR] AI files:', plan.files.length);
  console.log('[GENERATOR] ملفات AI المكتوبة:', writtenFiles);
  console.log('[GENERATOR] تم إنشاء المشروع بنجاح:', root);

  return root;
}

module.exports = {
  createFlutterBase,
  safeName
};
