const https = require('https');
const fs = require('fs');
const path = require('path');
const { execFile } = require('child_process');

function githubRequest(method, apiPath, token, body = null) {
  return new Promise((resolve, reject) => {
    const req = https.request({
      hostname: 'api.github.com',
      path: apiPath,
      method,
      headers: {
        Accept: 'application/vnd.github+json',
        Authorization: `Bearer ${token}`,
        'X-GitHub-Api-Version': '2022-11-28',
        'User-Agent': 'Mahani-Builder-AI',
        ...(body ? {
          'Content-Type': 'application/json',
          'Content-Length': Buffer.byteLength(body)
        } : {})
      }
    }, res => {
      let data = '';

      res.on('data', chunk => {
        data += chunk;
      });

      res.on('end', () => {
        let parsed = {};

        try {
          parsed = data ? JSON.parse(data) : {};
        } catch {
          return reject(
            new Error(`GitHub returned invalid JSON: HTTP ${res.statusCode}`)
          );
        }

        if (res.statusCode < 200 || res.statusCode >= 300) {
          const error = new Error(`GitHub API HTTP ${res.statusCode}`);
          error.status = res.statusCode;
          error.data = parsed;
          return reject(error);
        }

        resolve(parsed);
      });
    });

    req.on('error', reject);

    if (body) req.write(body);

    req.end();
  });
}

function runCommand(command, args, options = {}) {
  return new Promise((resolve, reject) => {
    execFile(command, args, {
      cwd: options.cwd,
      env: {
        ...process.env,
        ...(options.env || {})
      },
      maxBuffer: 20 * 1024 * 1024
    }, (error, stdout, stderr) => {
      if (error) {
        error.stdout = stdout;
        error.stderr = stderr;
        return reject(error);
      }

      resolve({
        stdout: stdout || '',
        stderr: stderr || ''
      });
    });
  });
}

function normalizeRepoName(name) {
  let value = String(name || 'mahani-app')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, '-')
    .replace(/^-+|-+$/g, '');

  if (!value) value = `mahani-app-${Date.now()}`;

  if (value.length > 90) {
    value = value.slice(0, 90);
  }

  return value;
}

async function getRepository(owner, repo, token) {
  try {
    return await githubRequest(
      'GET',
      `/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}`,
      token
    );
  } catch (error) {
    if (error.status === 404) return null;
    throw error;
  }
}

async function ensureRepository(owner, repo, token) {
  const existing = await getRepository(owner, repo, token);

  if (existing) {
    return existing;
  }

  console.log(`[GITHUB] Creating repository ${owner}/${repo}`);

  return githubRequest(
    'POST',
    '/user/repos',
    token,
    JSON.stringify({
      name: repo,
      description: 'Generated by Mahani Builder AI',
      private: false,
      has_issues: true,
      has_projects: false,
      has_wiki: false,
      auto_init: false
    })
  );
}

async function pushProjectToGitHub(owner, repo, token, projectPath) {
  if (!fs.existsSync(projectPath)) {
    throw new Error(`Project path not found: ${projectPath}`);
  }

  console.log(`[GITHUB] Preparing project ${projectPath}`);

  const gitDir = path.join(projectPath, '.git');

  if (fs.existsSync(gitDir)) {
    await runCommand('git', ['remote', 'remove', 'origin'], {
      cwd: projectPath
    }).catch(() => {});
  } else {
    await runCommand('git', ['init', '-b', 'main'], {
      cwd: projectPath
    });
  }

  const remoteUrl =
    `https://x-access-token:${encodeURIComponent(token)}` +
    `@github.com/${owner}/${repo}.git`;

  await runCommand('git', [
    'remote',
    'add',
    'origin',
    remoteUrl
  ], {
    cwd: projectPath
  });

  await runCommand('git', [
    'config',
    'user.name',
    'Mahani Builder AI'
  ], {
    cwd: projectPath
  });

  await runCommand('git', [
    'config',
    'user.email',
    'mahani-builder@users.noreply.github.com'
  ], {
    cwd: projectPath
  });

  await runCommand('git', ['add', '.'], {
    cwd: projectPath
  });

  await runCommand('git', [
    'commit',
    '-m',
    'feat: generate project with Mahani Builder AI'
  ], {
    cwd: projectPath
  }).catch(async error => {
    if (
      !String(error.stdout || '').includes('nothing to commit') &&
      !String(error.stderr || '').includes('nothing to commit')
    ) {
      throw error;
    }
  });

  await runCommand('git', [
    'push',
    '-u',
    'origin',
    'main',
    '--force'
  ], {
    cwd: projectPath
  });

  const shaResult = await runCommand('git', [
    'rev-parse',
    'HEAD'
  ], {
    cwd: projectPath
  });

  const commitSha = String(shaResult.stdout || '').trim();

  if (!commitSha) {
    throw new Error('لم يتم الحصول على commit SHA بعد push');
  }

  console.log(`[GITHUB] Project pushed to ${owner}/${repo}`);
  console.log(`[GITHUB] Commit SHA: ${commitSha}`);

  return {
    url: `https://github.com/${owner}/${repo}`,
    commitSha
  };
}

async function waitForWorkflowReady(owner, repo, workflowFile, token, timeout = 60000) {
  const started = Date.now();

  while (Date.now() - started < timeout) {
    try {
      const data = await githubRequest(
        'GET',
        `/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/actions/workflows`,
        token
      );

      const workflows = data.workflow_runs || data.workflows || [];

      const workflow = workflows.find(item =>
        item.path === workflowFile ||
        item.name === workflowFile ||
        item.html_url?.endsWith(workflowFile)
      );

      if (workflow && workflow.state === 'active') {
        console.log(`[GITHUB] Workflow ready: ${workflow.id}`);
        return workflow;
      }

      console.log('[GITHUB] Waiting for workflow registration...');
    } catch (error) {
      console.log('[GITHUB] Waiting for workflow API...');
    }

    await new Promise(resolve => setTimeout(resolve, 3000));
  }

  throw new Error('GITHUB_WORKFLOW_NOT_READY: workflow was not registered in time');
}

async function dispatchWorkflow(owner, repo, workflowFile, ref, token) {
  await githubRequest(
    'POST',
    `/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}` +
    `/actions/workflows/${encodeURIComponent(workflowFile)}/dispatches`,
    token,
    JSON.stringify({ ref })
  );
}

async function getWorkflowRuns(owner, repo, token) {
  return githubRequest(
    'GET',
    `/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}` +
    `/actions/runs?per_page=10`,
    token
  );
}

async function getWorkflowRun(owner, repo, runId, token) {
  return githubRequest(
    'GET',
    `/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}` +
    `/actions/runs/${runId}`,
    token
  );
}

async function waitForNewWorkflowRun(
  owner,
  repo,
  token,
  previousIds = []
) {
  for (let i = 0; i < 40; i++) {
    const data = await getWorkflowRuns(owner, repo, token);

    const run = (data.workflow_runs || []).find(
      item => !previousIds.includes(item.id)
    );

    if (run) return run;

    await new Promise(resolve => setTimeout(resolve, 3000));
  }

  throw new Error('لم يتم العثور على تشغيل GitHub Actions الجديد');
}

async function waitForWorkflowRunBySha(
  owner,
  repo,
  token,
  commitSha,
  timeout = 120000
) {
  const started = Date.now();

  while (Date.now() - started < timeout) {
    const data = await getWorkflowRuns(
      owner,
      repo,
      token
    );

    const runs = data.workflow_runs || [];

    const run = runs.find(item =>
      item.head_sha === commitSha &&
      item.event === 'push'
    );

    if (run) {
      console.log(`[GITHUB] Workflow run found: ${run.id}`);
      console.log(`[GITHUB] Run SHA: ${run.head_sha}`);
      console.log(`[GITHUB] Run status: ${run.status}`);
      return run;
    }

    await new Promise(resolve =>
      setTimeout(resolve, 3000)
    );
  }

  throw new Error(
    `لم يتم العثور على GitHub Actions Run للـ commit ${commitSha}`
  );
}

async function waitForWorkflowSuccess(
  owner,
  repo,
  runId,
  token,
  timeout = 20 * 60 * 1000
) {
  const started = Date.now();

  while (Date.now() - started < timeout) {
    const run = await getWorkflowRun(
      owner,
      repo,
      runId,
      token
    );

    console.log(
      `[GITHUB] Run ${run.id}: status=${run.status}, conclusion=${run.conclusion}`
    );

    if (run.status === 'completed') {
      if (run.conclusion !== 'success') {
        throw new Error(
          `GitHub Actions failed: ${run.conclusion || 'unknown'}`
        );
      }

      return run;
    }

    await new Promise(resolve => setTimeout(resolve, 10000));
  }

  throw new Error('GitHub Actions build timed out');
}

async function getRunArtifacts(owner, repo, runId, token) {
  return githubRequest(
    'GET',
    `/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}` +
    `/actions/runs/${runId}/artifacts`,
    token
  );
}

function downloadUrl(url, token) {
  return new Promise((resolve, reject) => {
    const requestUrl = new URL(url);

    const headers = {
      Accept: 'application/vnd.github+json',
      'User-Agent': 'Mahani-Builder-AI'
    };

    if (requestUrl.hostname === 'api.github.com') {
      headers.Authorization = `Bearer ${token}`;
      headers['X-GitHub-Api-Version'] = '2022-11-28';
    }

    const req = https.request({
      hostname: requestUrl.hostname,
      port: requestUrl.port || 443,
      path: requestUrl.pathname + requestUrl.search,
      method: 'GET',
      headers
    }, res => {
      if (
        res.statusCode >= 300 &&
        res.statusCode < 400 &&
        res.headers.location
      ) {
        return resolve(
          downloadUrl(res.headers.location, token)
        );
      }

      const chunks = [];

      res.on('data', chunk => chunks.push(chunk));

      res.on('end', () => {
        if (res.statusCode < 200 || res.statusCode >= 300) {
          return reject(
            new Error(
              `GitHub download failed: HTTP ${res.statusCode}`
            )
          );
        }

        resolve(Buffer.concat(chunks));
      });
    });

    req.on('error', reject);
    req.end();
  });
}

async function downloadArtifact(
  owner,
  repo,
  artifactId,
  token,
  outputZip
) {
  const url =
    `https://api.github.com/repos/${encodeURIComponent(owner)}` +
    `/${encodeURIComponent(repo)}` +
    `/actions/artifacts/${artifactId}/zip`;

  const buffer = await downloadUrl(url, token);

  fs.mkdirSync(path.dirname(outputZip), {
    recursive: true
  });

  fs.writeFileSync(outputZip, buffer);

  return outputZip;
}

async function extractApk(zipPath, outputDir) {
  fs.mkdirSync(outputDir, {
    recursive: true
  });

  await runCommand('unzip', [
    '-o',
    zipPath,
    '-d',
    outputDir
  ]);

  const apkPath = path.join(
    outputDir,
    'app-release.apk'
  );

  if (!fs.existsSync(apkPath)) {
    throw new Error(
      'app-release.apk not found inside GitHub artifact'
    );
  }

  return apkPath;
}

async function buildProject(
  owner,
  repo,
  token,
  projectPath,
  outputDir
) {
  const repository = await ensureRepository(
    owner,
    repo,
    token
  );

  console.log('[GITHUB] Pushing project to main...');

  const pushResult = await pushProjectToGitHub(
    owner,
    repo,
    token,
    projectPath
  );

  const repoUrl = pushResult.url;
  const commitSha = pushResult.commitSha;

  console.log(`[GITHUB] Waiting for workflow for commit ${commitSha}...`);

  const run = await waitForWorkflowRunBySha(
    owner,
    repo,
    token,
    commitSha
  );

  console.log(`[GITHUB] New workflow run: ${run.id}`);

  const completed = await waitForWorkflowSuccess(
    owner,
    repo,
    run.id,
    token
  );

  const artifacts = await getRunArtifacts(
    owner,
    repo,
    completed.id,
    token
  );

  const artifact =
    (artifacts.artifacts || []).find(
      item =>
        item.name === 'mahani_app-apk' &&
        item.expired === false
    ) ||
    (artifacts.artifacts || []).find(
      item =>
        String(item.name).toLowerCase().includes('apk') &&
        item.expired === false
    );

  if (!artifact) {
    throw new Error(
      'GitHub Actions succeeded but no APK artifact was found'
    );
  }

  const zipPath = path.join(
    outputDir,
    `artifact-${artifact.id}.zip`
  );

  await downloadArtifact(
    owner,
    repo,
    artifact.id,
    token,
    zipPath
  );

  const apkPath = await extractApk(
    zipPath,
    outputDir
  );

  return {
    repository: {
      name: repository.name,
      fullName: repository.full_name,
      url: repoUrl
    },
    runId: completed.id,
    workflowUrl: completed.html_url,
    artifactId: artifact.id,
    artifactName: artifact.name,
    apkPath,
    apkSize: fs.statSync(apkPath).size
  };
}

module.exports = {
  normalizeRepoName,
  githubRequest,
  ensureRepository,
  pushProjectToGitHub,
  dispatchWorkflow,
  getWorkflowRuns,
  getWorkflowRun,
  waitForNewWorkflowRun,
  waitForWorkflowSuccess,
  getRunArtifacts,
  downloadUrl,
  downloadArtifact,
  extractApk,
  buildProject
};
