const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const PACKAGE_VERSIONS = {
  equatable: '^2.1.0',
  cupertino_icons: '^1.0.8',
  provider: '^6.1.5',
  go_router: '^16.2.0',
  sqflite: '^2.4.2',
  drift: '^2.28.1',
  path: '^1.9.1',
  shared_preferences: '^2.5.3',
  intl: '^0.20.2',
  flutter_local_notifications: '^19.4.0',
  pdf: '^3.11.3',
  printing: '^5.14.2',
  excel: '^4.0.6',
  file_picker: '^10.3.2',
  permission_handler: '^12.0.1',
  path_provider: '^2.1.5',
  http: '^1.5.0',
  uuid: '^4.5.1',
  crypto: '^3.0.6'
};

const MODEL = undefined || 'nvidia/nemotron-3-super-120b-a12b:free';

function safeProjectName(name) {
  return String(name || 'mahani_app')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .replace(/_+/g, '_')
    .slice(0, 50) || `mahani_app_${Date.now()}`;
}

function root(projectName) {
  return path.join(
    __dirname,
    'projects',
    safeProjectName(projectName)
  );
}


function createFlutterAndroidProject(projectName, plan) {
  const projectRoot = root(projectName);
  const projectNameSafe = safeProjectName(projectName);

  fs.mkdirSync(
    path.dirname(projectRoot),
    { recursive: true }
  );

  console.log(
    '[ENGINE] إنشاء Flutter Android project حقيقي'
  );

  if (
    fs.existsSync(projectRoot) &&
    fs.existsSync(path.join(projectRoot, 'android'))
  ) {
    console.log(
      '[ENGINE] Android project موجود بالفعل'
    );
    return projectRoot;
  }

  if (fs.existsSync(projectRoot)) {
    fs.rmSync(
      projectRoot,
      {
        recursive: true,
        force: true
      }
    );
  }

  execFileSync(
    'flutter',
    [
      'create',
      '--platforms=android',
      '--project-name',
      projectNameSafe,
      projectRoot
    ],
    {
      stdio: 'inherit',
      timeout: 180000
    }
  );

  // Normalize Dart SDK constraint so the generated project
  // remains compatible with the Flutter version used by GitHub Actions.
  const generatedPubspec = path.join(
    projectRoot,
    'pubspec.yaml'
  );

  if (fs.existsSync(generatedPubspec)) {
    let pubspecContent = fs.readFileSync(
      generatedPubspec,
      'utf8'
    );

    pubspecContent = pubspecContent.replace(
      /^\s*sdk:\s*\^3\.\d+\.\d+\s*$/m,
      "    sdk: '>=3.9.0 <4.0.0'"
    );

    fs.writeFileSync(
      generatedPubspec,
      pubspecContent,
      'utf8'
    );

    console.log(
      '[ENGINE] Dart SDK constraint normalized to >=3.9.0 <4.0.0'
    );
  }

  if (
    !fs.existsSync(
      path.join(projectRoot, 'android')
    )
  ) {
    throw new Error(
      'FLUTTER_CREATE_FAILED: مجلد android لم يتم إنشاؤه'
    );
  }

  // Normalize Kotlin Android Gradle configuration generated by Flutter.
  // Prevents `kotlin { compilerOptions { jvmTarget = ... } }`
  // from failing when the Kotlin Android plugin is missing.
  const androidAppGradle = path.join(
    projectRoot,
    'android',
    'app',
    'build.gradle.kts'
  );

  if (fs.existsSync(androidAppGradle)) {
    let gradleContent = fs.readFileSync(
      androidAppGradle,
      'utf8'
    );

    const kotlinPlugin = '    id("org.jetbrains.kotlin.android")';

    if (
      !gradleContent.includes(
        'id("org.jetbrains.kotlin.android")'
      )
    ) {
      const androidPlugin = '    id("com.android.application")';

      if (!gradleContent.includes(androidPlugin)) {
        throw new Error(
          'FLUTTER_ANDROID_GRADLE_PATCH_FAILED: com.android.application plugin not found'
        );
      }

      gradleContent = gradleContent.replace(
        androidPlugin,
        androidPlugin + '\\n' + kotlinPlugin,
        1
      );

      fs.writeFileSync(
        androidAppGradle,
        gradleContent,
        'utf8'
      );

      console.log(
        '[ENGINE] Kotlin Android plugin added automatically'
      );
    } else {
      console.log(
        '[ENGINE] Kotlin Android plugin already present'
      );
    }
  } else {
    throw new Error(
      'FLUTTER_ANDROID_GRADLE_PATCH_FAILED: android/app/build.gradle.kts not found'
    );
  }


  if (
    !fs.existsSync(
      path.join(projectRoot, 'pubspec.yaml')
    )
  ) {
    throw new Error(
      'FLUTTER_CREATE_FAILED: pubspec.yaml لم يتم إنشاؤه'
    );
  }

  console.log(
    '[ENGINE] تم إنشاء Flutter Android project بنجاح'
  );

  return projectRoot;
}

async function askAI(apiKey, messages, maxTokens = 5000) {
  const { execFile } = require('child_process');

  const models = [
    'nvidia/nemotron-3-super-120b-a12b:free',
    ...(process.env.GROQ_API_KEY ? ['groq/openai/gpt-oss-20b'] : []),
    'openai/gpt-oss-20b:free',
    'cohere/north-mini-code:free'
  ].filter((value, index, array) =>
    value && array.indexOf(value) === index
  );

  const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));

  function extractJson(text) {
    let clean = String(text || '')
      .replace(/^```json\s*/i, '')
      .replace(/^```\s*/i, '')
      .replace(/\s*```$/i, '')
      .trim();

    try {
      return JSON.parse(clean);
    } catch (_) {}

    const first = clean.indexOf('{');
    const last = clean.lastIndexOf('}');

    if (first >= 0 && last > first) {
      const candidate = clean.slice(first, last + 1);
      try {
        return JSON.parse(candidate);
      } catch (_) {}
    }

    throw new Error(
      'AI returned invalid/incomplete JSON: ' +
      clean.slice(0, 3000)
    );
  }

  function callCurl(model, tokenLimit) {
    const isGroq = model.startsWith('groq/');
    const provider = isGroq ? 'Groq' : 'OpenRouter';

    const actualModel = isGroq
      ? model.slice(5)
      : model;

    const endpoint = isGroq
      ? 'https://api.groq.com/openai/v1/chat/completions'
      : 'https://openrouter.ai/api/v1/chat/completions';

    const providerKey = isGroq
      ? process.env.GROQ_API_KEY
      : apiKey;

    if (!providerKey) {
      throw new Error(provider + ' API key is missing');
    }

    const payloadObject = {
      model: actualModel,
      messages,
      temperature: 0,
      response_format: { type: 'json_object' }
    };

    if (isGroq) {
      payloadObject.max_completion_tokens = tokenLimit;
    } else {
      payloadObject.max_tokens = tokenLimit;
    }

    const payload = JSON.stringify(payloadObject);

    console.log(
      '[AI] provider=' + provider +
      ' model=' + actualModel +
      ' tokens=' + tokenLimit
    );

    return new Promise((resolve, reject) => {
      execFile(
        'curl',
        [
          '--silent',
          '--show-error',
          '--fail-with-body',
          '--connect-timeout', '30',
          '--max-time', '120',
          endpoint,
          '-H', 'Authorization: Bearer ' + providerKey,
          '-H', 'Content-Type: application/json',

          ...(isGroq
            ? []
            : [
                '-H', 'HTTP-Referer: http://127.0.0.1:3000',
                '-H', 'X-Title: Mahani Builder AI'
              ]),

          '--data', payload
        ],
        {
          maxBuffer: 30 * 1024 * 1024
        },
        (error, stdout, stderr) => {
          const raw = String(stdout || '').trim();
          const err = String(stderr || '').trim();

          let data = null;

          if (raw) {
            try {
              data = JSON.parse(raw);
            } catch (_) {}
          }

          if (error) {
            const providerError =
              data && data.error
                ? JSON.stringify(data.error)
                : raw.slice(0, 5000);

            reject(new Error(
              provider + ' curl failed: ' +
              (err || error.message) +
              '; RESPONSE=' +
              providerError
            ));
            return;
          }

          if (!data) {
            reject(new Error(
              provider + ' returned empty JSON'
            ));
            return;
          }

          if (data.error) {
            reject(new Error(
              provider + ' API error: ' +
              JSON.stringify(data.error).slice(0, 5000)
            ));
            return;
          }

          const choice = data.choices?.[0];
          const finish =
            choice?.finish_reason || 'unknown';

          const content =
            choice?.message?.content;

          console.log(
            '[AI] model=' +
            (data.model || actualModel) +
            ' provider=' +
            (data.provider || provider) +
            ' tokens=' +
            tokenLimit +
            ' finish=' +
            finish +
            ' content=' +
            (typeof content === 'string'
              ? content.length
              : 0)
          );

          if (!content) {
            reject(new Error(
              'AI returned no content: finish_reason=' +
              finish +
              '; usage=' +
              JSON.stringify(
                data.usage || {}
              ).slice(0, 3000)
            ));
            return;
          }

          try {
            resolve(extractJson(content));
          } catch (jsonError) {
            reject(new Error(
              jsonError.message +
              '; finish_reason=' +
              finish
            ));
          }
        }
      );
    });
  }

  const firstLimit = Math.min(
    Math.max(2500, Number(maxTokens) || 6000),
    9000
  );

  let lastError = null;

  for (const model of models) {
    console.log('');
    console.log('[AI] محاولة النموذج: ' + model);

    try {
      console.log('[AI] tokens=' + firstLimit);
      return await callCurl(model, firstLimit);

    } catch (firstError) {
      lastError = firstError;

      const msg = String(firstError.message || '');

      console.log(
        '[AI] فشل النموذج ' + model + ':'
      );
      console.log(msg);

      // 401: توقف فوريًا لأن المفتاح نفسه غير صالح.
      if (/401|invalid.*api.*key|authentication/i.test(msg)) {
        throw new Error(
          'OPENROUTER_AUTH_FAILED: ' + msg
        );
      }

      // 429: لا تعيد المحاولة بنفس النموذج.
      // وإذا كان الحد اليومي عامًا، لا تحرق بقية الطلبات.
      if (
        /429|free-models-per-day|rate.?limit|too many requests/i.test(msg)
      ) {
        console.log(
          '[AI] 429 — تم إيقاف إعادة المحاولة لهذا النموذج'
        );

        if (/free-models-per-day/i.test(msg)) {
          lastError = new Error(
            'OPENROUTER_FREE_DAILY_LIMIT_REACHED'
          );
          continue;
        }

        await sleep(1500);
        continue;
      }

      // 402 / credits / quota
      if (/402|payment|insufficient|credits|quota/i.test(msg)) {
        console.log(
          '[AI] الرصيد/الحصة غير متاحة — النموذج التالي'
        );
        continue;
      }

      // Timeout / 5xx:
      // تجربة واحدة فقط بحجم أصغر.
      if (
        /500|502|503|504|timeout|timed out|curl failed/i.test(msg)
      ) {
        console.log(
          '[AI] خطأ مؤقت — محاولة أصغر مرة واحدة'
        );

        try {
          return await callCurl(
            model,
            Math.max(3000, Math.floor(firstLimit * 0.55))
          );
        } catch (secondError) {
          lastError = secondError;
          console.log(
            '[AI] فشلت المحاولة المختصرة — النموذج التالي'
          );
          continue;
        }
      }

      // JSON غير صالح أو إخراج مبتور:
      // لا نكرر 8000 token؛ ننتقل للنموذج التالي.
      if (
        /invalid.*json|incomplete.*json|finish_reason=length/i.test(msg)
      ) {
        console.log(
          '[AI] JSON غير صالح/مبتور — النموذج التالي'
        );
        continue;
      }

      continue;
    }
  }

  if (
    lastError &&
    lastError.message === 'OPENROUTER_FREE_DAILY_LIMIT_REACHED'
  ) {
    throw new Error(
      'OPENROUTER_FREE_DAILY_LIMIT_REACHED: ' +
      'تم استنفاد حد OpenRouter المجاني اليومي. ' +
      'لن يتم حرق طلبات إضافية بإعادة المحاولة.'
    );
  }

  throw new Error(
    'AI generation failed: all fallback models failed. LAST=' +
    (lastError ? lastError.message : 'unknown error')
  );
}

function buildGenerationPrompt(
  plan,
  stage,
  existingFiles
) {
  const limits = {
    core: 1,
    data: 2,
    services: 2,
    ui: 3
  };

  const maxFiles = limits[stage] || 2;

  const existing = Array.isArray(existingFiles)
    ? existingFiles.slice(-40)
    : [];

  return `
Create the current stage of a real Flutter application.

APP:
${JSON.stringify(plan)}

STAGE:
${stage}

MAX FILES:
${maxFiles}

EXISTING FILES:
${JSON.stringify(existing)}

Rules:
- JSON only.
- Output exactly: {"files":[...]}
- Maximum ${maxFiles} files.
- Every file must be complete Dart code.
- Every path must start with lib/ and end with .dart.
- Dart 3.9+ and Flutter stable.
- No TODO.
- No placeholder.
- No fake data.
- No Markdown.
- No explanations.
- No Future.delayed.
- No imports of files that do not exist.
- No unavailable packages.
- Arabic UI must support RTL.
- Keep the code compact.
- Do not recreate existing files unnecessarily.
- The project must remain compilable.

Stage instructions:
core = application entry point and minimum foundation only.
data = models and real local data persistence only.
services = required application services only.
ui = minimum functional user interface only.

Return JSON only:
{
  "files": [
    {
      "path": "lib/example.dart",
      "purpose": "short purpose",
      "content": "complete Dart code"
    }
  ]
}
`;
}


function collectDartContext(projectName, maxFiles = 40, maxCharsPerFile = 14000, maxTotalChars = 90000) {
  const projectRoot = root(projectName);
  const files = collectFiles(projectName);
  const result = [];
  let total = 0;

  for (const relative of files.slice(0, maxFiles)) {
    const full = path.join(projectRoot, relative);

    if (!fs.existsSync(full)) {
      continue;
    }

    let content = fs.readFileSync(full, 'utf8');

    if (content.length > maxCharsPerFile) {
      content =
        content.slice(0, maxCharsPerFile) +
        '\n\n// [CONTEXT TRUNCATED]\n';
    }

    if (total + content.length > maxTotalChars) {
      break;
    }

    result.push({
      path: relative,
      content
    });

    total += content.length;
  }

  return result;
}

function generateStage(
  apiKey,
  plan,
  stage,
  existingFiles
) {
  const projectName = safeProjectName(
    plan?.appName || plan?.name || 'mahani_app'
  );
  const stageLimits = {
    core: 1,
    data: 2,
    services: 2,
    ui: 3
  };

  const maxFiles = stageLimits[stage] || 2;

  // Build a real project context from the current Dart files.
  // This gives every generation stage access to actual source code,
  // not only a list of filenames.
  const contextMaxFiles =
      stage === 'core' ? 8 :
      stage === 'ui' ? 8 : 24;

    const contextMaxCharsPerFile =
      stage === 'core' ? 6000 :
      stage === 'ui' ? 4000 : 9000;

    const contextMaxTotalChars =
      stage === 'core' ? 18000 :
      stage === 'ui' ? 18000 : 60000;

    const projectContext = collectDartContext(
      projectName,
      contextMaxFiles,
      contextMaxCharsPerFile,
      contextMaxTotalChars
    );

  const compactPrompt = `
You are a senior Flutter production engineer working inside Mahani Builder AI.

Generate ONLY the current stage of a real Flutter application.

PROJECT:
${JSON.stringify(plan)}

CURRENT STAGE:
${stage}

MAXIMUM FILES:
${maxFiles}

CURRENT PROJECT CONTEXT:
${JSON.stringify(projectContext).slice(0, stage === 'core' ? 12000 : 24000)}

EXISTING FILE PATHS:
${JSON.stringify(existingFiles).slice(0, stage === 'core' ? 6000 : 12000)}

STRICT RULES:
- Return JSON only.
- Return exactly one object with a "files" array.
- Generate no more than ${maxFiles} files.
- Every file must be a complete Dart source file.
- Every path must start with lib/ and end with .dart.
- Never use TODO.
- Never use placeholder code.
- Never use fake or mock data.
- Never use Future.delayed.
- Never put Markdown inside content.
- Never import a file that does not exist.
- Never import an unavailable package.
- Use only real Flutter/Dart code.
- Dart 3.9+ and current Flutter stable.
- Arabic interfaces must use RTL.
- Keep the implementation compact.
- Do not generate unnecessary files.
- Do not repeat existing files unless required.
- The result must compile as part of a real Flutter project.
- Build only what is necessary for the current stage.
- Do not explain anything outside the JSON.

STAGE RULES:

core:
                                              Generate ONLY the minimum runnable application foundation.
                                              Prefer exactly lib/main.dart.
                                              Do not plan.
                                              Do not explain.
                                              Do not describe your reasoning.
                                              Do not output prose.
                                              Return the final JSON immediately.
                                              main.dart must be complete and compilable.

data:
Create only the minimum models/database/data-layer files required by the application.
Use real local persistence when required by the project.

services:
Create only the minimum service files required by the project.
Do not duplicate data-layer code.

ui:
Create only the minimum UI files required to make the application functional.
Use existing files from previous stages.
Do not create a huge interface.

OUTPUT FORMAT:
{
  "files": [
    {
      "path": "lib/main.dart",
      "purpose": "short purpose",
      "content": "complete Dart source"
    }
  ]
}
`;

  return askAI(
    apiKey,
    [
      {
        role: 'system',
        content: 'You are a senior Flutter production engineer. Output valid JSON only. Be concise and generate complete compilable code.'
      },
      {
        role: 'user',
        content: compactPrompt
      }
    ],
    stage === 'core' ? 4500 :
                          stage === 'data' ? 5500 :
                          stage === 'services' ? 5500 :
                          stage === 'ui' ? 4500 : 5000
  );
}


function normalizeLocalPackageImports(projectName, source) {
  const projectPackage = safeProjectName(projectName);

  return String(source || '').replace(
    /package:([a-zA-Z0-9_]+)\//g,
    (full, packageName) => {
      // Keep the current project's own package imports unchanged.
      if (packageName === projectPackage) {
        return full;
      }

      // Keep every known external Flutter/Dart package unchanged.
      if (PACKAGE_VERSIONS[packageName]) {
        return full;
      }

      // Flutter SDK packages must ALWAYS remain external imports.
      if (
        packageName === 'flutter' ||
        packageName === 'flutter_localizations' ||
        packageName === 'cupertino'
      ) {
        return full;
      }

      // Unknown package imports are left untouched.
      // The validator will report them if the dependency is missing.
      return full;
    }
  );
}

function writeFiles(projectName, files) {
  const projectRoot = root(projectName);
  const libRoot = path.join(
    projectRoot,
    'lib'
  );

  fs.mkdirSync(
    libRoot,
    { recursive: true }
  );

  let written = 0;

  for (
    const file of Array.isArray(files)
      ? files
      : []
  ) {
    if (
      !file ||
      typeof file !== 'object'
    ) {
      continue;
    }

    const relative = String(
      file.path || ''
    ).trim();

    if (
      !relative.startsWith('lib/') ||
      relative.includes('..') ||
      relative.includes('\\') ||
      !relative.endsWith('.dart')
    ) {
      continue;
    }

    const full = path.resolve(
      projectRoot,
      relative
    );

    if (
      !full.startsWith(
        path.resolve(libRoot) +
        path.sep
      )
    ) {
      continue;
    }

    const content = normalizeLocalPackageImports(
      projectName,
      String(file.content || '').trim()
    );

    if (!content) continue;

    fs.mkdirSync(
      path.dirname(full),
      { recursive: true }
    );

    fs.writeFileSync(
      full,
      content + '\n',
      'utf8'
    );

    written++;
  }

  return written;
}

function collectFiles(projectName) {
  const projectRoot = root(projectName);
  const result = [];

  if (!fs.existsSync(projectRoot)) {
    return result;
  }

  function walk(dir) {
    for (
      const item of fs.readdirSync(
        dir,
        { withFileTypes: true }
      )
    ) {
      const full = path.join(
        dir,
        item.name
      );

      if (item.isDirectory()) {
        walk(full);
      } else if (
        item.isFile() &&
        item.name.endsWith('.dart')
      ) {
        result.push(
          path.relative(
            projectRoot,
            full
          )
        );
      }
    }
  }

  walk(
    path.join(
      projectRoot,
      'lib'
    )
  );

  return result.sort();
}

function collectAllProjectFiles(projectName) {
  const projectRoot = root(projectName);

  if (!fs.existsSync(projectRoot)) {
    return [];
  }

  const result = [];

  function walk(dir) {
    for (
      const item of fs.readdirSync(
        dir,
        { withFileTypes: true }
      )
    ) {
      const full = path.join(
        dir,
        item.name
      );

      if (item.isDirectory()) {
        walk(full);
      } else {
        result.push(
          path.relative(
            projectRoot,
            full
          )
        );
      }
    }
  }

  walk(projectRoot);

  return result.sort();
}

function detectImportedPackages(
  projectName
) {
  const projectRoot = root(projectName);
  const packages = new Set();

  for (
    const relative of collectFiles(projectName)
  ) {
    const full = path.join(
      projectRoot,
      relative
    );

    const source = fs.readFileSync(
      full,
      'utf8'
    );

    const regex =
      /import\s+['"]package:([^/]+)\//g;

    let match;

    while (
      (match = regex.exec(source))
    ) {
      const packageName = match[1];

      if (
        PACKAGE_VERSIONS[packageName]
      ) {
        packages.add(packageName);
      }
    }
  }

  return [...packages].sort();
}

function validateGeneratedFiles(
  projectName
) {
  const projectRoot = root(projectName);

  const errors = [];

  const files =
    collectFiles(projectName);

  if (!files.includes('lib/main.dart')) {
    errors.push(
      'lib/main.dart غير موجود'
    );
  }

  const pubspecPath = path.join(
    projectRoot,
    'pubspec.yaml'
  );

  if (!fs.existsSync(pubspecPath)) {
    errors.push(
      'pubspec.yaml غير موجود'
    );
  }

  const importedPackages =
    detectImportedPackages(projectName);

  for (
    const packageName of importedPackages
  ) {
    if (
      !PACKAGE_VERSIONS[packageName]
    ) {
      errors.push(
        `Package غير معروف: ${packageName}`
      );
    }
  }

  return {
    valid: errors.length === 0,
    errors,
    files,
    importedPackages
  };
}


function createPubspec(projectName, plan) {
  const projectRoot = root(projectName);
  const pubspecPath = path.join(projectRoot, 'pubspec.yaml');

  fs.mkdirSync(projectRoot, { recursive: true });
  fs.mkdirSync(path.join(projectRoot, 'lib'), { recursive: true });

  const dependencies = Object.entries(PACKAGE_VERSIONS)
    .map(([name, version]) => '  ' + name + ': ' + version)
    .join('\n');

  const description = String(
    plan?.idea || plan?.description || 'Flutter application'
  )
    .replace(/\r?\n/g, ' ')
    .replace(/"/g, '\\"')
    .slice(0, 200);

  const content =
`name: ${safeProjectName(projectName)}
description: "${description}"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
${dependencies}

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
`;

  fs.writeFileSync(pubspecPath, content, 'utf8');

  return pubspecPath;
}


function ensureFlutterPubspecDependencies(projectName, plan) {
  const projectRoot = root(projectName);

  const pubspecPath = path.join(
    projectRoot,
    'pubspec.yaml'
  );

  if (!fs.existsSync(pubspecPath)) {
    throw new Error(
      'PUBSPEC_NOT_FOUND: Flutter project did not create pubspec.yaml'
    );
  }

  let content = fs.readFileSync(
    pubspecPath,
    'utf8'
  );

  const dependencies = {
    flutter_localizations: null,
    ...PACKAGE_VERSIONS
  };

  const lines = content.split(/\r?\n/);

  let dependenciesIndex = lines.findIndex(
    line => line.trim() === 'dependencies:'
  );

  if (dependenciesIndex === -1) {
    throw new Error(
      'PUBSPEC_INVALID: dependencies section not found'
    );
  }

  let dependenciesEnd = lines.findIndex(
    (line, index) =>
      index > dependenciesIndex &&
      line.length > 0 &&
      !line.startsWith(' ') &&
      !line.startsWith('#')
  );

  if (dependenciesEnd === -1) {
    dependenciesEnd = lines.length;
  }

  const existing = new Set();

  for (
    let i = dependenciesIndex + 1;
    i < dependenciesEnd;
    i++
  ) {
    const match = lines[i].match(
      /^  ([a-zA-Z0-9_]+):/
    );

    if (match) {
      existing.add(match[1]);
    }
  }

  const additions = [];

  if (!existing.has('flutter_localizations')) {
    additions.push(
      '  flutter_localizations:',
      '    sdk: flutter'
    );
  }

  for (const [name, version] of Object.entries(
    PACKAGE_VERSIONS
  )) {
    if (existing.has(name)) {
      continue;
    }

    additions.push(
      '  ' + name + ': ' + version
    );
  }

  if (additions.length > 0) {
    lines.splice(
      dependenciesEnd,
      0,
      ...additions
    );
  }

  content = lines.join('\n');

  fs.writeFileSync(
    pubspecPath,
    content,
    'utf8'
  );

  console.log(
    '[ENGINE] Flutter pubspec dependencies configured'
  );

  return pubspecPath;
}


async function prepareFlutterBuild(projectName) {
  const projectRoot = root(projectName);

  if (!fs.existsSync(projectRoot)) {
    throw new Error(
      'FLUTTER_BUILD_PREP_FAILED: project root not found'
    );
  }

  console.log(
    '[ENGINE] تشغيل flutter pub get'
  );

  execFileSync(
    'flutter',
    ['pub', 'get'],
    {
      cwd: projectRoot,
      stdio: 'inherit',
      timeout: 300000
    }
  );

  console.log(
    '[ENGINE] تشغيل flutter analyze'
  );

  try {
    execFileSync(
      'flutter',
      ['analyze', 'lib'],
      {
        cwd: projectRoot,
        stdio: 'inherit',
        timeout: 300000
      }
    );
  } catch (error) {
    throw new Error(
      'FLUTTER_ANALYZE_FAILED: flutter analyze failed'
    );
  }

  console.log(
    '[ENGINE] Flutter project passed analyze'
  );

  return true;
}


function buildFlutterApk(projectName) {
  const projectRoot = root(projectName);

  if (!fs.existsSync(projectRoot)) {
    throw new Error(
      'APK_BUILD_FAILED: project root not found'
    );
  }

  console.log(
    '[ENGINE] بدء flutter build apk --release'
  );

  try {
    execFileSync(
      'flutter',
      [
        'build',
        'apk',
        '--release'
      ],
      {
        cwd: projectRoot,
        stdio: 'inherit',
        timeout: 600000
      }
    );
  } catch (error) {
    throw new Error(
      'FLUTTER_APK_BUILD_FAILED: flutter build apk --release failed'
    );
  }

  const apkCandidates = [
    path.join(
      projectRoot,
      'build',
      'app',
      'outputs',
      'flutter-apk',
      'app-release.apk'
    ),
    path.join(
      projectRoot,
      'build',
      'app',
      'outputs',
      'apk',
      'release',
      'app-release.apk'
    )
  ];

  const apkPath = apkCandidates.find(
    file => fs.existsSync(file)
  );

  if (!apkPath) {
    throw new Error(
      'APK_NOT_FOUND: Flutter build succeeded but APK was not found'
    );
  }

  console.log(
    '[ENGINE] تم إنشاء APK بنجاح: ' + apkPath
  );

  return apkPath;
}



async function repairFlutterProject(
  apiKey,
  projectName,
  plan,
  maxAttempts = 3
) {
  const projectRoot = root(projectName);

  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    console.log(
      `[ENGINE] محاولة إصلاح Flutter ${attempt}/${maxAttempts}`
    );

    let analyzeOutput = '';

    try {
      analyzeOutput = execFileSync(
        'flutter',
        ['analyze', 'lib'],
        {
          cwd: projectRoot,
          encoding: 'utf8',
          stdio: ['ignore', 'pipe', 'pipe'],
          timeout: 300000
        }
      );
    } catch (error) {
      analyzeOutput =
        String(error.stdout || '') +
        '\n' +
        String(error.stderr || '');
    }

    analyzeOutput = analyzeOutput.trim();

    if (!analyzeOutput) {
      console.log(
        '[ENGINE] flutter analyze لم يرجع أخطاء'
      );
      return true;
    }

    if (
      /No issues found!/i.test(analyzeOutput) ||
      /0 issues found/i.test(analyzeOutput)
    ) {
      console.log(
        '[ENGINE] Flutter project صالح'
      );
      return true;
    }

    // Flutter analyze may report warnings/info even when the
    // application has no compilation errors. Do NOT send these
    // harmless diagnostics to the AI repair loop.
    const errorMatches = analyzeOutput.match(
      /(?:^|\\n)\\s*error\\s*[•:]/gi
    );

    const errorCount = errorMatches
      ? errorMatches.length
      : 0;

    if (errorCount === 0) {
      console.log(
        '[ENGINE] Flutter صالح — لا توجد أخطاء error حقيقية'
      );
      console.log(
        '[ENGINE] تم تجاهل warnings/info غير المانعة للبناء'
      );
      return true;
    }

    console.log(
      `[ENGINE] أخطاء Flutter الحقيقية: ${errorCount}`
    );
    console.log(analyzeOutput.slice(0, 16000));

    const dartFiles = collectFiles(projectName);

    const relevantFiles = [];

    for (const relative of dartFiles) {
      const full = path.join(
        projectRoot,
        relative
      );

      if (!fs.existsSync(full)) {
        continue;
      }

      let content = fs.readFileSync(
        full,
        'utf8'
      );

      if (content.length > 18000) {
        content =
          content.slice(0, 18000) +
          '\n\n// [FILE CONTEXT TRUNCATED]\n';
      }

      relevantFiles.push({
        path: relative,
        content
      });
    }

    const projectContext = {
      files: relevantFiles,
      fileCount: relevantFiles.length,
      packageFiles: collectAllProjectFiles(projectName)
        .filter(file => /^(pubspec\.yaml|analysis_options\.yaml)$/.test(file))
    };

    const repairPrompt = `
You are repairing an existing real Flutter application.

Do NOT redesign the application.
Do NOT create a new application.
Do NOT remove existing functionality.
Do NOT use TODO.
Do NOT use placeholder code.
Do NOT use fake data.
Do NOT explain anything outside JSON.

The application MUST compile with current Flutter stable and Dart 3.9+.

PROJECT PLAN:
${JSON.stringify(plan)}

REAL FLUTTER ANALYZE OUTPUT:
${analyzeOutput.slice(0, 16000)}

CURRENT PROJECT CONTEXT:
${JSON.stringify(projectContext).slice(0, 24000)}

YOUR TASK:
1. Diagnose the actual compilation/analyzer errors.
2. Fix the existing Dart files.
3. Keep the existing architecture and UI design.
4. Make models, services, data sources and UI APIs consistent.
5. Never invent an API that does not exist.
6. Flutter SDK localization must use valid Flutter APIs.
7. TextDirection must use valid Dart/Flutter values.
8. Do not modify pubspec.yaml.
9. Do not generate test files.
10. Return ONLY files that must be changed.
11. Every returned file must contain its COMPLETE Dart source.
12. Every path must start with lib/ and end with .dart.
13. Maximum 8 files.

OUTPUT:
{
  "files": [
    {
      "path": "lib/example.dart",
      "purpose": "why this file must be fixed",
      "content": "complete Dart source"
    }
  ]
}
`;

    let result;

    try {
      result = await askAI(
        apiKey,
        [
          {
            role: 'system',
            content:
              'You are a senior Flutter debugging engineer. Return valid JSON only. Fix compilation errors in existing code.'
          },
          {
            role: 'user',
            content: repairPrompt
          }
        ],
        8000
      );
    } catch (error) {
      throw new Error(
        'FLUTTER_AUTO_REPAIR_AI_FAILED: ' +
        error.message
      );
    }

    const files =
      Array.isArray(result?.files)
        ? result.files
        : [];

    if (!files.length) {
      throw new Error(
        'FLUTTER_AUTO_REPAIR_EMPTY: AI returned no repair files'
      );
    }

    const written = writeFiles(
      projectName,
      files
    );

    if (!written) {
      throw new Error(
        'FLUTTER_AUTO_REPAIR_WRITE_FAILED: no files written'
      );
    }

    console.log(
      `[ENGINE] تم إصلاح ${written} ملف`
    );

    try {
      execFileSync(
        'flutter',
        ['pub', 'get'],
        {
          cwd: projectRoot,
          stdio: 'inherit',
          timeout: 300000
        }
      );
    } catch (error) {
      throw new Error(
        'FLUTTER_AUTO_REPAIR_PUB_GET_FAILED: ' +
        error.message
      );
    }
  }

  throw new Error(
    `FLUTTER_AUTO_REPAIR_FAILED: flutter analyze still fails after ${maxAttempts} attempts`
  );
}

function ensureProject(projectName, plan) {
  const projectRoot = root(projectName);

  fs.mkdirSync(projectRoot, { recursive: true });
  fs.mkdirSync(path.join(projectRoot, 'lib'), { recursive: true });

  const pubspecPath = path.join(projectRoot, 'pubspec.yaml');

  if (!fs.existsSync(pubspecPath)) {
    createPubspec(projectName, plan);
  }

  return projectRoot;
}

function validateDartConsistency(projectName) {
  const projectRoot = root(projectName);
  const libRoot = path.join(projectRoot, 'lib');
  const errors = [];

  if (!fs.existsSync(libRoot)) {
    return { valid: false, errors: ['lib directory غير موجود'] };
  }

  const dartFiles = [];

  function walk(dir) {
    for (const item of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, item.name);

      if (item.isDirectory()) {
        walk(full);
      } else if (item.isFile() && item.name.endsWith('.dart')) {
        dartFiles.push(full);
      }
    }
  }

  walk(libRoot);

  const relativeDartFiles = new Set(
    dartFiles.map(full =>
      path.relative(libRoot, full).split(path.sep).join('/')
    )
  );

  let packageName = safeProjectName(projectName);

  const pubspecPath = path.join(projectRoot, 'pubspec.yaml');

  if (fs.existsSync(pubspecPath)) {
    const pubspec = fs.readFileSync(pubspecPath, 'utf8');
    const match = pubspec.match(/^name:\s*([A-Za-z0-9_]+)\s*$/m);

    if (match) {
      packageName = match[1];
    }
  }

  const declarations = new Map();
  const allSource = new Map();

  for (const full of dartFiles) {
    const relative = path.relative(libRoot, full)
      .split(path.sep)
      .join('/');

    const source = fs.readFileSync(full, 'utf8');

    allSource.set(relative, source);

    const names = [
      ...source.matchAll(
        /\b(?:class|enum|mixin|extension)\s+([A-Za-z_]\w*)/g
      )
    ].map(m => m[1]);

    for (const name of names) {
      if (!declarations.has(name)) {
        declarations.set(name, []);
      }

      declarations.get(name).push(relative);
    }
  }

  for (const [relative, source] of allSource) {
    const imports = [
      ...source.matchAll(/import\s+['"]([^'"]+)['"]/g)
    ].map(m => m[1]);

    for (const importPath of imports) {

      if (importPath.startsWith('package:')) {
        const match = importPath.match(/^package:([^/]+)\/(.+)$/);

        if (!match) {
          errors.push(
            relative + ': package import غير صالح: ' + importPath
          );
          continue;
        }

        const importedPackage = match[1];
        const importedFile = match[2];

        if (importedPackage === packageName) {
          if (!relativeDartFiles.has(importedFile)) {
            errors.push(
              relative +
              ': import داخلي غير موجود: ' +
              importPath
            );
          }
        } else if (!PACKAGE_VERSIONS[importedPackage]) {
          errors.push(
            relative +
            ': package غير موجود في PACKAGE_VERSIONS: ' +
            importedPackage
          );
        }
      }

      if (
        importPath.startsWith('../') ||
        importPath.startsWith('./')
      ) {
        const currentDir = path.posix.dirname(relative);

        const normalized = path.posix.normalize(
          path.posix.join(currentDir, importPath)
        );

        if (!relativeDartFiles.has(normalized)) {
          errors.push(
            relative +
            ': relative import غير موجود: ' +
            importPath
          );
        }
      }
    }
  }

  // Generic project consistency validation.
  // يتم الاعتماد على:
  // 1. صحة مسارات Dart الداخلية.
  // 2. وجود الملفات المستوردة.
  // 3. وجود الحزم المعروفة.
  // 4. وجود lib/main.dart.
  // 5. سلامة اسم package في pubspec.
  const uniqueErrors = [...new Set(errors)];

  return {
    valid: uniqueErrors.length === 0,
    errors: uniqueErrors,
    dartFiles: relativeDartFiles.size,
    packageName
  };
}


function writeGitHubWorkflow(projectName) {
  const projectRoot = root(projectName);

  const workflowDir = path.join(
    projectRoot,
    '.github',
    'workflows'
  );

  const workflowPath = path.join(
    workflowDir,
    'build-apk.yml'
  );

  fs.mkdirSync(workflowDir, {
    recursive: true
  });

  const workflow = [
    'name: Mahani Builder - Android APK',
    '',
    'on:',
    '  workflow_dispatch:',
    '  push:',
    '    branches:',
    '      - main',
    '',
    'permissions:',
    '  contents: read',
    '',
    'jobs:',
    '  build:',
    '    runs-on: ubuntu-latest',
    '',
    '    steps:',
    '      - name: Checkout repository',
    '        uses: actions/checkout@v4',
    '',
    '      - name: Setup Java 17',
    '        uses: actions/setup-java@v5',
    '        with:',
    '          distribution: temurin',
    "          java-version: '17'",
    '',
    '      - name: Setup Flutter',
    '        uses: subosito/flutter-action@v2',
    '        with:',
    "          flutter-version: '3.35.7'",
    '          channel: stable',
    '          cache: true',
    '',
    '      - name: Verify environment',
    '        run: |',
    '          set -e',
    '          flutter --version',
    '          dart --version',
    '          java -version',
    '',
    '      - name: Get dependencies',
    '        run: flutter pub get',
    '',
    '      - name: Analyze project',
    '        run: flutter analyze',
    '',
    '      - name: Build release APK',
    '        run: flutter build apk --release',
    '',
    '      - name: Verify APK',
    '        shell: bash',
    '        run: |',
    '          set -e',
    '',
    '          APK="build/app/outputs/flutter-apk/app-release.apk"',
    '',
    '          if [ ! -f "$APK" ]; then',
    '            echo "ERROR: APK was not created"',
    '            find build -type f -name "*.apk" -print || true',
    '            exit 1',
    '          fi',
    '',
    '          echo "APK CREATED SUCCESSFULLY"',
    '          ls -lh "$APK"',
    '',
    '      - name: Upload APK',
    '        uses: actions/upload-artifact@v4',
    '        with:',
    '          name: mahani_app-apk',
    '          path: build/app/outputs/flutter-apk/app-release.apk',
    '          if-no-files-found: error',
    '          retention-days: 7',
    ''
  ].join('\n');

  fs.writeFileSync(
    workflowPath,
    workflow,
    'utf8'
  );

  console.log(
    '[ENGINE] GitHub Actions workflow created: ' +
    workflowPath
  );

  return workflowPath;
}


async function analyzeFlutterProject(projectName) {
  const projectRoot = root(projectName);

  try {
    execFileSync(
      'flutter',
      ['analyze', 'lib'],
      {
        cwd: projectRoot,
        encoding: 'utf8',
        stdio: ['ignore', 'pipe', 'pipe'],
        timeout: 300000
      }
    );

    return {
      passed: true,
      output: 'No issues found'
    };
  } catch (error) {
    const output =
      String(error.stdout || '') +
      '\n' +
      String(error.stderr || '');

    return {
      passed: false,
      output: output.trim()
    };
  }
}

async function runStageSafely(
  apiKey,
  projectName,
  plan,
  stage,
  existingFiles,
  maxRepairAttempts = 3
) {
  console.log('');
  console.log('============================================================');
  console.log(`[PIPELINE] بدء المرحلة: ${stage}`);
  console.log('============================================================');

  // GitHub-only pipeline:
  // AI generates the Dart files locally.
  // Flutter validation and APK build happen ONLY on GitHub Actions.

  const result = await generateStage(
    apiKey,
    plan,
    stage,
    existingFiles
  );

  const files = Array.isArray(result?.files)
    ? result.files
    : [];

  if (!files.length) {
    throw new Error(
      `STAGE_${stage.toUpperCase()}_EMPTY: AI لم يولد ملفات`
    );
  }

  const written = writeFiles(
    projectName,
    files
  );

  if (!written) {
    throw new Error(
      `STAGE_${stage.toUpperCase()}_WRITE_FAILED: لم يتم كتابة أي ملف`
    );
  }

  const validation = validateGeneratedFiles(
    projectName
  );

  if (!validation.valid) {
    throw new Error(
      `STAGE_${stage.toUpperCase()}_VALIDATION_FAILED: ` +
      validation.errors.join('; ')
    );
  }

  console.log(
    `[PIPELINE] ${stage} generated successfully — Flutter validation deferred to GitHub Actions`
  );

  return {
    files: collectDartContext(projectName),
    generated: files.length,
    written,
    repaired: false,
    repairAttempts: 0,
    analysis: 'Deferred to GitHub Actions'
  };
}

async function buildProject(
  apiKey,
  projectName,
  plan
) {
  if (!apiKey) {
    throw new Error(
      'OPENROUTER_API_KEY غير موجود'
    );
  }

  const projectRoot =
    createFlutterAndroidProject(
      projectName,
      plan
    );

  ensureFlutterPubspecDependencies(
    projectName,
    plan
  );

  console.log(
    '[ENGINE] Flutter Android project + dependencies configured'
  );

  const stages = [
    'core',
    'data',
    'services',
    'ui'
  ];

    // ============================================================
    // MAHANI CHECKPOINT / RESUME
    // ============================================================

    const checkpointPath = path.join(
      projectRoot,
      '.mahani-checkpoint.json'
    );

    let checkpoint = {
      version: 2,
      projectName,
      appName: plan?.appName || '',
      description: plan?.description || '',
      appType: plan?.appType || '',
      design: plan?.design || '',
      completedStages: [],
      results: []
    };

    if (fs.existsSync(checkpointPath)) {
      try {
        const saved = JSON.parse(
          fs.readFileSync(checkpointPath, 'utf8')
        );

        if (
          saved &&
          (saved.version === 1 || saved.version === 2) &&
          saved.projectName === projectName &&
          Array.isArray(saved.completedStages)
        ) {
          checkpoint = saved;

          console.log(
            '[CHECKPOINT] تم استعادة حالة البناء السابقة'
          );

          console.log(
            '[CHECKPOINT] المراحل المكتملة: ' +
            checkpoint.completedStages.join(', ')
          );
        }
      } catch (error) {
        console.log(
          '[CHECKPOINT] الحالة السابقة غير صالحة — بدء جديد'
        );
      }
    }

    const results = Array.isArray(checkpoint.results)
      ? checkpoint.results
      : [];

    let existingFiles = collectDartContext(projectName);

    for (const stage of stages) {
      if (checkpoint.completedStages.includes(stage)) {
        console.log(
          `[CHECKPOINT] التحقق من المرحلة المحفوظة: ${stage}`
        );

        const savedAnalysis =
          await analyzeFlutterProject(projectName);

        if (savedAnalysis.passed) {
          console.log(
            `[CHECKPOINT] تخطي ${stage} — المشروع صالح`
          );

          existingFiles =
            collectDartContext(projectName);

          continue;
        }

        console.log(
          `[CHECKPOINT] ${stage} محفوظة لكن المشروع غير صالح — إعادة المرحلة`
        );

        checkpoint.completedStages =
          checkpoint.completedStages.filter(
            item => item !== stage
          );

        checkpoint.results =
          results.filter(
            item => item.stage !== stage
          );

        fs.writeFileSync(
          checkpointPath,
          JSON.stringify(checkpoint, null, 2),
          'utf8'
        );
      }

      console.log(
        `[ENGINE] بدء المرحلة الآمنة: ${stage}`
      );

      try {
        const stageResult =
          await runStageSafely(
            apiKey,
            projectName,
            plan,
            stage,
            existingFiles,
            3
          );

        existingFiles =
          stageResult.files;

        results.push({
          stage,
          generated: stageResult.generated,
          written: stageResult.written,
          repaired: stageResult.repaired,
          repairAttempts:
            stageResult.repairAttempts || 0,
          files: existingFiles.length,
          completedAt:
            new Date().toISOString()
        });

        checkpoint.completedStages.push(stage);
        checkpoint.results = results;

        fs.writeFileSync(
          checkpointPath,
          JSON.stringify(checkpoint, null, 2),
          'utf8'
        );

        console.log(
          `[CHECKPOINT] تم حفظ ${stage} بعد نجاح analyze`
        );

      } catch (error) {
        checkpoint.results = results;

        fs.writeFileSync(
          checkpointPath,
          JSON.stringify(checkpoint, null, 2),
          'utf8'
        );

        console.log(
          `[CHECKPOINT] توقف البناء عند ${stage}`
        );

        console.log(
          `[CHECKPOINT] السبب: ${error.message}`
        );

        throw error;
      }
    }

    if (
      checkpoint.completedStages.length === stages.length
    ) {
      try {
        fs.unlinkSync(checkpointPath);

        console.log(
          '[CHECKPOINT] اكتملت جميع مراحل AI — تم حذف checkpoint'
        );
      } catch (error) {
        console.log(
          '[CHECKPOINT] تعذر حذف checkpoint: ' +
          error.message
        );
      }
    }

console.log(
    '[ENGINE] التحقق من ملفات المشروع قبل GitHub Actions'
  );

  let validation =
    validateGeneratedFiles(
      projectName
    );

  if (!validation.valid) {
    throw new Error(
      `PROJECT_VALIDATION_FAILED: ${validation.errors.join('; ')}`
    );
  }

    // GitHub-only build pipeline.
  // Flutter pub get, analyze, repair and APK build run on GitHub Actions only.
  console.log(
    '[ENGINE] GitHub-only pipeline: local Flutter execution skipped'
  );

  writeGitHubWorkflow(projectName);

  const githubActions = require('./github-actions');

  const githubOwner = String(
    process.env.GITHUB_OWNER || ''
  ).trim();

  const githubToken = String(
    process.env.GITHUB_TOKEN || ''
  ).trim();

  if (!githubOwner) {
    throw new Error(
      'GITHUB_BUILD_FAILED: GITHUB_OWNER غير موجود في .env'
    );
  }

  if (!githubToken) {
    throw new Error(
      'GITHUB_BUILD_FAILED: GITHUB_TOKEN غير موجود في .env'
    );
  }

  const githubOutputDir = path.join(
    projectRoot,
    'github-build'
  );

  fs.mkdirSync(githubOutputDir, {
    recursive: true
  });

  console.log(
    '[ENGINE] بدء البناء الحقيقي عبر GitHub Actions'
  );

  const githubBuild =
    await githubActions.buildProject(
      githubOwner,
      projectName,
      githubToken,
      projectRoot,
      githubOutputDir
    );

  const apkPath = githubBuild.apkPath;

  console.log(
    '[ENGINE] تم إنشاء APK عبر GitHub Actions: ' +
    apkPath
  );

  return {
    projectRoot,
    apkPath,
    github: githubBuild,
    files: collectAllProjectFiles(
      projectName
    ),
    dartFiles: collectFiles(
      projectName
    ),
    importedPackages:
      validation.importedPackages,
    stages: results,
    validation
  };
}

module.exports = {
  MODEL,
  PACKAGE_VERSIONS,
  safeProjectName,
  root,
  createPubspec,
  ensureProject,
  buildProject,
  collectFiles,
  collectDartContext,
  collectAllProjectFiles,
  writeGitHubWorkflow,
  detectImportedPackages,
  validateGeneratedFiles
};
